# @deprecated use semantic-release
name: npm-publish
on:
  push:
    tags:
      - "v*"
jobs:
  npm-publish:
    if: github.repository == 'snolab/CapsLockX'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
      - run: bun install
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
